package com.is442.autograder.generation;

import com.is442.autograder.model.GeneratedTestCase;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.Properties;

/**
 * Writes the final generated tester Java file, merging original and generated
 * test cases. Backs up the original tester before writing.
 */
public class TesterFileWriter {

	/**
	 * Write a generated tester file to the output folder.
	 *
	 * @param testerClassName
	 *            e.g. "Q1aTester"
	 * @param originalCode
	 *            content of the original tester (may be null)
	 * @param generatedCode
	 *            raw code blocks from Claude
	 * @param cases
	 *            test cases with professor-assigned weights
	 * @param originalTesterDir
	 *            directory containing original tester file (for backup)
	 * @param outputDir
	 *            where to write the generated file
	 * @return path of the written file
	 */
	public Path write(String testerClassName, String originalCode, String generatedCode, List<GeneratedTestCase> cases,
			Path originalTesterDir, Path outputDir) throws IOException {

		Files.createDirectories(outputDir);

		// Back up original if it exists
		if (originalTesterDir != null) {
			Path originalFile = originalTesterDir.resolve(testerClassName + ".java");
			if (Files.exists(originalFile)) {
				Files.copy(originalFile, originalFile.resolveSibling(testerClassName + ".java.bak"),
						StandardCopyOption.REPLACE_EXISTING);
			}
		}

		String generatedClassName = testerClassName + "_generated";
		String parentClass = testerClassName.replace("Tester", "");

		// Substitute WEIGHT_N placeholders with actual weights
		String codeWithWeights = substituteWeights(generatedCode, cases);

		String fileContent = buildFileContent(generatedClassName, parentClass, originalCode, codeWithWeights);

		Path outputFile = outputDir.resolve(generatedClassName + ".java");
		Files.writeString(outputFile, fileContent);
		return outputFile;
	}

	/**
	 * Update the max score for a question in config.properties.
	 *
	 * @param configPath
	 *            path to config.properties
	 * @param questionId
	 *            e.g. "Q1a"
	 * @param newMaxScore
	 *            new total max score
	 */
	public void updateConfigMaxScore(Path configPath, String questionId, double newMaxScore) throws IOException {
		if (!Files.exists(configPath)) {
			return;
		}

		Properties props = new Properties();
		try (InputStream is = Files.newInputStream(configPath)) {
			props.load(is);
		}

		String[] ids = props.getProperty("questions.list", "").split(",", -1);
		String[] scores = props.getProperty("questions.max.scores", "").split(",", -1);

		for (int i = 0; i < ids.length; i++) {
			if (ids[i].trim().equalsIgnoreCase(questionId)) {
				scores[i] = String.valueOf(newMaxScore);
				break;
			}
		}

		props.setProperty("questions.max.scores", String.join(",", scores));

		// Write back preserving comments as best as possible
		String content = Files.readString(configPath);
		String oldScoresLine = props.getProperty("questions.max.scores");
		// Rebuild the scores value
		String newScoresValue = String.join(",", scores);
		content = content.replaceFirst("(?m)^questions\\.max\\.scores=.*$", "questions.max.scores=" + newScoresValue);
		Files.writeString(configPath, content);
	}

	private String substituteWeights(String code, List<GeneratedTestCase> cases) {
		String result = code;
		for (int i = 0; i < cases.size(); i++) {
			result = result.replace("WEIGHT_" + (i + 1), String.valueOf(cases.get(i).weight()));
		}
		// Replace any remaining WEIGHT_N placeholders with 1.0
		result = result.replaceAll("WEIGHT_\\d+", "1.0");
		return result;
	}

	private String buildFileContent(String generatedClassName, String parentClass, String originalCode,
			String generatedCode) {
		StringBuilder sb = new StringBuilder();
		sb.append("// Auto-generated by IS442 AutoGrader — review before use\n");
		sb.append("import java.util.*;\n\n");
		sb.append("public class ").append(generatedClassName).append(" extends ").append(parentClass).append(" {\n\n");
		sb.append("    private static double score = 0;\n");
		sb.append("    private static String qn = \"").append(parentClass).append("\";\n\n");
		sb.append("    public static void main(String[] args) {\n");
		sb.append("        grade();\n");
		sb.append("        System.out.println(score);\n");
		sb.append("    }\n\n");
		sb.append("    public static void grade() {\n");

		if (originalCode != null && !originalCode.isBlank()) {
			// Extract grade() body from original — it already contains the banner
			// and int tcNum = 1; so we do NOT add them again here.
			String gradeBody = extractGradeBody(originalCode);
			if (!gradeBody.isBlank()) {
				sb.append("\n        // ── Original test cases (preserved) ─────────────────────────\n");
				sb.append(gradeBody);
				sb.append("\n");
			}
		} else {
			// From-scratch: add banner and tcNum declaration
			sb.append("        System.out.println(\"-------------------------------------------------------\");\n");
			sb.append(
					"        System.out.println(\"---------------------- \" + qn + \" ----------------------------\");\n");
			sb.append("        System.out.println(\"-------------------------------------------------------\");\n\n");
			sb.append("        int tcNum = 1;\n");
		}

		sb.append("\n        // ── Generated test cases ─────────────────────────────────────\n");
		// Indent generated blocks
		for (String line : generatedCode.split("\n")) {
			sb.append("        ").append(line).append("\n");
		}

		// Balance any unclosed braces from the generated code so the file always
		// compiles. We track depth starting after the grade() opening brace (depth=0
		// means we are at grade-body level).
		int depth = countBraceDepth(sb, "    public static void grade() {\n");
		for (int i = 0; i < depth; i++) {
			sb.append("        }\n");
		}

		sb.append("    }\n"); // close grade()
		sb.append("}\n"); // close class
		return sb.toString();
	}

	/**
	 * Count net brace depth within a StringBuilder starting after a marker line.
	 * Returns the number of unclosed '{' that need matching '}'.
	 */
	private int countBraceDepth(StringBuilder sb, String startMarker) {
		int startIdx = sb.indexOf(startMarker);
		if (startIdx < 0) {
			return 0;
		}
		startIdx += startMarker.length();

		int depth = 0;
		boolean inString = false;
		boolean inLineComment = false;
		boolean inBlockComment = false;
		char prev = 0;

		for (int i = startIdx; i < sb.length(); i++) {
			char c = sb.charAt(i);

			if (inLineComment) {
				if (c == '\n') {
					inLineComment = false;
				}
			} else if (inBlockComment) {
				if (prev == '*' && c == '/') {
					inBlockComment = false;
				}
			} else if (inString) {
				if (c == '"' && prev != '\\') {
					inString = false;
				}
			} else {
				if (c == '/' && i + 1 < sb.length()) {
					char next = sb.charAt(i + 1);
					if (next == '/') {
						inLineComment = true;
					} else if (next == '*') {
						inBlockComment = true;
					}
				} else if (c == '"' && prev != '\\') {
					inString = true;
				} else if (c == '{') {
					depth++;
				} else if (c == '}') {
					depth--;
				}
			}
			prev = c;
		}
		return Math.max(depth, 0);
	}

	/**
	 * Extract the body of the grade() method from existing tester code (without the
	 * method signature and braces).
	 */
	private String extractGradeBody(String code) {
		int gradeStart = code.indexOf("public static void grade()");
		if (gradeStart < 0) {
			gradeStart = code.indexOf("static void grade()");
		}
		if (gradeStart < 0) {
			return "";
		}

		// Find opening brace
		int braceOpen = code.indexOf('{', gradeStart);
		if (braceOpen < 0) {
			return "";
		}

		// Find matching closing brace
		int depth = 1;
		int i = braceOpen + 1;
		while (i < code.length() && depth > 0) {
			char c = code.charAt(i);
			if (c == '{') {
				depth++;
			} else if (c == '}') {
				depth--;
			}
			i++;
		}

		// Extract content between the outer braces
		return code.substring(braceOpen + 1, i - 1);
	}
}
