services:
  docling:
    image: ghcr.io/docling-project/docling-serve:latest
    ports: 
      - "5001:5001"
    restart: always

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DOCLING_SERVE_URL=http://docling:5001
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    depends_on:
      - docling
    volumes:
      - ./output:/app/output
    restart: always


  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  plagiarism-viewer:
    build: ./plagiarism-viewer
    ports:
      - "1996:80"
    depends_on:
      - backend
    restart: always
